### ISSUE TITLE
Install phpmyadmin into a PHP App Server instance

### ISSUE THREAD

**Issue by fabioce** [aporat/opsworks-php-cookbooks#7]
Hello,
Which is the procedure to install phpmyadmin into an instance of a layer "php app server" of a stack of opsworks?

Thanks

**Comment by aporat** [comment]
Hi,

I never tried configuring phpmyadmin directly on opsworks, as I keep database instances locked down inside a VPC.

on vagrant I include this portion on the vagrant setup recipe :

```
include_recipe "phpmyadmin::default"

phpmyadmin_db 'Dev DB' do
  host 'db.xxxxxxx.us-east-1.rds.amazonaws.com'
  port 3306
  username 'root'
  password ''
  auth_type 'http'
end

```

hopes it helps
